using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using AngleSharp;
using AngleSharp.Html.Parser;
using AngleSharp.Html.Dom;
using AngleSharp.Dom;

using Gemipedia.Converter.Filter;
using Gemipedia.Models;

namespace Gemipedia.Converter
{
	/// <summary>
    /// Takes HTML generated by media wiki, and converts it into GemText
    /// </summary>
	public class WikiHtmlConverter
	{
        ConverterSettings Settings;

        public WikiHtmlConverter(ConverterSettings settings)
        {
            Settings = settings;
            CommonUtils.Settings = settings;

            LoadDomFilters();
        }

        private void LoadDomFilters()
        {
            DomFilter.Global = new DomFilter();
            //DomFilter.Global.AddRule("")
        }


        public ParsedPage Convert(string title, string wikiHtml)
        {

            var contentRoot = Preparer.PrepareHtml(wikiHtml);

            Sectionizer sectionizer = new Sectionizer(Settings);

            var parsedPage = sectionizer.ParseContent(title, contentRoot);

            ConvertSections(parsedPage.Sections);

            return parsedPage;
        }

        private void ConvertSections(List<Section> sections)
            => sections.ForEach(x => ConvertSection(x));

        private void ConvertSection(Section section)
        {
            HtmlParser htmlParser = new HtmlParser();
            foreach(var node in section.Nodes)
            {
                htmlParser.Parse(node);
            }

            section.AddItems(htmlParser.GetItems());
            ConvertSections(section.SubSections);
        }
    }
}

