using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using AngleSharp;
using AngleSharp.Html.Parser;
using AngleSharp.Html.Dom;
using AngleSharp.Dom;

using Gemipedia.NGConverter.Models;

namespace Gemipedia.NGConverter
{
	/// <summary>
    /// Takes HTML generated by media wiki, and converts it into GemText
    /// </summary>
	public class NGWikiHtmlConverter
	{
        ConverterSettings Settings;


        public NGWikiHtmlConverter(ConverterSettings settings)
        {
            Settings = settings;
            CommonUtils.Settings = settings;
        }

        public void Convert(string title, string wikiHtml, TextWriter textWriter)
        {

            var contentRoot = Preparer.PrepareHtml(wikiHtml);

            Sectionizer sectionizer = new Sectionizer(Settings);

            var parsedPage = sectionizer.ParseContent(title, contentRoot);

            ConvertSections(parsedPage.Sections);

            ArticleRenderer renderer = new ArticleRenderer(Settings);
            renderer.RenderArticle(parsedPage, textWriter);

            //now ready to render

            int x = 5;

        }
        private void ConvertSections(List<Section> sections)
            => sections.ForEach(x => ConvertSection(x));


        private void ConvertSection(Section section)
        {
            HtmlParser htmlParser = new HtmlParser();
            foreach(var node in section.Nodes)
            {
                htmlParser.Parse(node);
            }

            section.AddItems(htmlParser.GetItems());
            ConvertSections(section.SubSections);
        }
 

    }
}

